worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8080

dbconnection: 'postgresql://YetAnotherDiskOpenAPI_user:password@localhost:5432/YetAnotherDiskOpenAPI_db-1'
